# Game settings

# Players

player:
    - human
    - AI

# Difficuly levels

difficulty: 
    - beginner
    - intermediate
    - expert
    - champion
    - custom

# Models

model_folder: /agents/game_models

model_file:
    beginnner: /beginner
    intermediate: /intermediate
    expert: /expert
    champion: /champion
    custom: /custom

input_units:
    beginner: 198
    intermediate: 198
    expert: 250
    champion: 250
    custom: 198

hidden_units: 
    beginner: 80
    intermediate: 80
    expert: 80
    champion: 80
    custom: 80

n_ply:
    beginner: 1
    intermediate: 1
    expert: 1
    champion: 2
    custom: 1